FIN103.STP/GPI+++September 14, 2021+++ 16:05:30+++ UTC+1  

INTERNATIONAL SWIFT ACKS9662-9CUSTOMER’S COPY  

-------------------------------------------------- INSTANCE TYPE ANDTRANSMISSION ----------------------------------------------- 

RCVD++ NOTIFICATION (TRANSMISSION) OF ORIGINAL SENT TO SWIFT (ACK)  

RCVD++ NETWORK DELIVERY STATUS: NETWORK ACK 

RCVD++ PRIORITY DELIVERY: NORMAL  

RCVD++ MESSAGE OUTPUT REFERENCE: 1409202144711DEUT103966254921  

RCVD++ MESSAGE INPUT REFERENCE: 14092021144711DEUT103371114921881  

 ----------------------------------------------------- MESSAGE APPLICATIONHEADER ----------------------------------------------- 

RCVD++ SWIFT OUTPUT: MT103 GPI WIRE TRANSFER  

RCVD++ SENDER: 

RCVD++ SENDER’S BANK NAME: DEUTSCHE BANK AG   

RCVD++ SENDER’S BANK ADDRESS: AM BUCHBAUM 12A, D-60437 FRANKFURT AM MAIN, GERMANY Y  

RCVD++ SENDER’S ACCOUNT NAME: T:XO GMBH  

RCVD++ SENDER’S ACCOUNT NUMBER: DE92 5007 0024 0023 3437 00  

RCVD++ SENDER’S SWIFT CODE: DEUTDEDBFRA  

RCVD++ SENDER’S BANK OFFICER NAME: vinita.chejara  

RCVD++ SENDER’S BANK OFFICER EMAIL: vinita.chejara@db.com  

RCVD++ SENDER’S TELEPHONE: +49 69 910-00  

RCVD++ SENDER’S GLOBAL SERVER IP: 193.150.166.0/24 /193.150.166.0/243  

RCVD++ SENDER’S IMAD NUMBER: 27C DB FR DE 17BEH  

RCVD++ SENDER’S WTS SERVER: LOT/S005635 / S0200235 

RCVD++ AMOUNT/CURRENCY: €980.000.00€ EURO€ 

RCVD++RCVD++ RECEIVER: 

RCVD++ RECEIVER’S: BANK NAME: YAPI VE KREDİ BANKASI ANONİM ŞİRKETİ TURKEY 

RCVD++ RECEIVER’S: BANK ADDRESS: 22 NİSAN MH. 75 YIL BLV.A BLOK NO:5A/11-12 NİLÜFER-BURSA 

RCVD++ RECEIVER’S ACCOUNT NAME: ÖMER AYATA TUĞRA ENERJI 

RCVD++ RECEIVER’S ACCOUNT NUMBER: TR37 0006 7010 0000 0077 4458 81   

RCVD++ RECEIVER’S SWIFT CODE: YAPITRISXXX   

RCVD++ RECEIVER’S BANK OFFICER NAME: LEVENT YENIGUN 

RCVD++ RECEIVER’S BANK OFFICER EMAIL:  

RCVD++ RECEIVER’S TELEPHONE:   

RCVD++ RECEIVER’S GLOBAL SERVER IP: 172.31.32.88 TURKEY 

RCVD++ RECEIVER’S IMAD NUMBER: ec2-3-120-16-55.eu-central-TR  

RCVD++ RECEIVER’S WTS:T96O1253,125PP96TR  

RCVD++ AMOUNT/CURRENCY: €980,000,00€ EURO€ 
 ----------------------------------------------------------------------------------------------------------------------------- 
RCVD++ 108: MESSAGE USER PREFERENCE  

RCVD++ MIR: 273215804901  

RCVD++ 119 VALIDATION FLAG: STP  

RCVD++ SERVICE TYPE IDENTIFIER: 111:001  

RCVD++: 121: UNIQUE-END-TO-END-TRANSACTION-REFERENCE UETR : [a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12 

----------------------------------------------------- MESSAGE TEXT ------------------------------------------------------------- 

***F20: TRANSACTION REFERENCE: DEUT67232757-Y706ZY  

***F21: TRANSACTION CODE: GSS-CUS-KZNBRU7485306PLTY 

***DEPOSIT CODE: DB79056588 DTSZS/N°.79056-CA-79055  

***PERMIT ARRIVA MONEY NUMBER: SCF-85O96H95TY159  

***FED CODE: F–211009154.G943–19–9543–126859–698  

***F23B: BANK OPERATION CODE: CRED  

***F32A: VAL DATE/CURR/INTERBANK SETTLEMENT  

DATE: SAME DAY  

CURRENCY: EUR  

AMOUNT: € 980,000.00  

***F33B: CURRENCY/INSTRUCTED AMOUNT: € 980,000.00(Nine hundred and eighty thousand euros )  

***F50A: ORDERING CUSTOMER NAME & ADDRESS: T XO GMBH/60437 FRANKFURT - GERMANY  

***F52A: ORDERING ACCOUNT: / FI / DE92500700240023343700   /DEUTDEDBFRA  

***F59A: BENEFICIARY CUSTOMER NAME&ADDRESS: API VE KREDİ BANKASI ANONİM ŞİRKETİ /YURKEY/ YAPITRISXXX / TR370006701000000077445881  

***F70: REMITTANCE INFORMATION INVESTMENT  

***F71A: DETAILS OF CHARGES OURS: BEN  

***F72: SENDER TO RECEIVER’S INFORMATION: // PLEASE ADVISE THE BENEFICIARY OF THIS SWIFT. 

// THIS TRANSFER IS VALID FOR PAYMENT THE DAY OF RECEIPT. 

// THIS IRREVOCABLE CASH BACKED SWIFT MT103 GPI TRANSFER  

***F77B: REGULATORY REPORTING: // € 980,000.00(Nine hundred and eighty thousand euros)  

// OPERATIVE INSTRUMENT NO MAIL OR SWIFT SERVICE LEVEL IS REQUIRED. 

*** F79: NARRATIVE 

MANDATORY FIELDS: MT 103  

F23B: BANK OPERATION  
--------------------------------------------------------------------------------------------------------------------------------- 
F32A: VALUE DATE/CURRENCY/INTERBANK SETTLED DATE  

DATE: September 14, 2021  

TIME: 16:05:30  

CURRENCY: EUR  
 -------------- ------------------------------------------------------------------------------------------------------------------------- 
DEUTANZB114HU85RY69  

PKI TURKYE MAC EQUIVALENT  

--------------------------------------------------------------------------------------------------------------------------------- 

APPLICATION: SWIFT INTERFACE  

OPERATION: SYSTEM  

END TIME: September 14, 2021 16:05:30  

TEXT (DEUTANZBZAUSN07 5847 JU78 50 00)  

:1)FO1 BPKOPLPW5899JO0215/PL311596857560000180202158558 

  -------------------------------------------------------------------------------------------------------------------------------------- 

(1//SENDER AMOUNT: €980,000.00 #EURO# 

(2//RECEIVER CODE: 13817425894IO/101825843  

(3//PROVIDER CODE: A23F17.10.37 47 GTF5  

(4//TRANSMITTING BANK: DEUTSCHE BANK AG  

(5//BANK ADDRESS: TAUNUSANLAGE 12,60325 FRANKFURT AM MAIN GERMANY  

(6//SWIFT CODE: DEUTDEDBFRA  

(7//DEPOSIT CODE: DB79056588 ARTS/N°.79056-CA-79055  

(8//GLOBAL_CODE: TLTQTLOPS504.5569OKTD/259  

(9//REFERENCE CODE: JIE/.58GU4957 /58569 

(10/FEDS CODE: F–21091405154.G943–1069–9543–8969–342  

(11/SECURITY CODE: SET BY RECEIVER BANK  

(12/MILLION/BILLION DEPARTAMENT FRANKFURT: ART/Y - LAW -- 21 - FRANKFURT GOVERNMENT, TCL75342 /13( 

ONE - TIME SATELLITE SWIFT DOWNLOAD ACCESS WITHDRAW CODE: 5267958696 

WE HEREBY CONFIRM WITH FULL BANKING RESPONSIBILITY THAT THE ABOVE FUNDS ARE GOOD, CLEAN, CLEAR AND TAXED //FUNDS OF NON-        CRIMINAL ORIGIN, FREE FROM ANY LIENS OR ENCUMBRANCES AND PAID FOR INVESTMENT MT103 IS FOR //IMMEDIATE CREDIT-INSTANT SAME DAY    VALUE AND NO MAIL OR SWIFT CONFIRMATION SHALL FOLLOW. 

   --------------------------------------------------------------------------------------------------------------------------------
TRANSMISSION CODES  

1 .FINAL CODE: DEUT-679585236987/4586LO56  

2 .SORT CODE: 678 691 681  

3 .TRANSACTION CODE: 5794661  

4 .ACCESS CODE: ANZ5269UJ85NH9  

5 .KEY CODE: DEUT51009215869KOL94  

6 .FINAL BLOCKING CODE: KKTUCDEW695863KBVZD  

7 .RELEASE CODE: 325967854  

8 .RECEIVING_CODE: 114586PPLK96TY1596  

 ------------------------------------------------------------------------------------------------------------------------------------ 

WE, DEUTSCHE BANK AG LOCATED AT TAUNUSANLAGE 12,60325 FRANKFURT AM MAIN GERMANY, WITH FULL BANK  

RESPONSIBILITY HEREBY  

PRESENT OUR UNCONDITIONAL, IRREVOCABLE, ASSIGNABLE, TRANSFERABLE, AND CALLABLE CASH-BACKED STANDING S.W.I.F.  

T MT103  

GPI TRANSFER IN FAVOR OF "T XO GMBH PMP PROSPERSP.ZO.O." WITH ACCOUNT NUMBER: DE92500700240023343700 IN THE AMOUNT OF 980,000.00 #EURO#  

(Nine hundred and eighty thousand euros) THIS FUND IS FOR INVESTMENT PURPOSES. 

WE HEREBY CONFIRM THAT THESE FUNDS ARE GOOD, CLEAN, AND CLEARED FUNDS OF NON-CRIMINAL ORIGIN ARE FROM  

LEGAL SOURCES.THIS  

IRREVOCABLE, SWIFT MT 103 WIRE TRANSFER IS BINDING FULLY PERFORMED DUE BILL AND IMMEDIATELY CALLABLE FOR  

CASH PAYMENT, 

WE CONFIRM THAT THE PAYMENT SHOULD BE RELEASED IMMEDIATELY. 

THIS UNCONDITIONAL, IRREVOCABLE, ASSIGNABLE, TRANSFERABLE, AND CALLABLE MT 103 GPI S.W.I.F.T IS VALID FOR ONE  

YEAR OF  

RECEIPT WITHOUT PRESENTATION OF IT TO US AND WITHOUT PAYMENT OF ANY TRANSFER OR ASSIGNMENT FEES. 

THIS IS AN OPERATIVE INSTRUMENT FOR AND ON BEHALF OF DEUTSCHE BANK AG LOCATED AT TAUNUSANLAGE 12,-60325  

FRANKFURT AM  

MAIN GERMANY, SUBJECT TO THE YAPI VE KREDİ BANKASI ANONİM ŞİRKETİ AND SUBJECT TO  ACCOUNT TR370006701000000077445881 

ACCOUNT NAME ÖMER AYATA TUĞRA ENERJI 

PAYMENT AND IS  

VALID FOR ONE YEAR. 

NO FURTHER CONFIRMATION EITHER BY FAX OR MAIL AFTER THIS MESSAGE. 

ALL ISSUING BANK CHARGES ARE FOR THE ACCOUNT OF ITS APPLICANT . 

RECORD INFORMATION SWIFT ORDER IS MAC: (PAC) (PEG ENC) DEBZA (INT) PED) (MAC). FORAND ON BEHALF OFDEUTSCHE BANK AG 60254 ,FRANKFURT AM MAIN, GERMANY  

  ------------------------------------------------------------------------------------------------------------------------------------ 
1110000000010233413877 : YAPIBAU3M  

CONF: DATE: September 14, 2021+++ 16:05:30+++ UTC+1  

D-60437 FRANKFURT AM MAIN, GERMANY 

+++681 691 678+++MSG+++555 TITLE  

YAPI569: DEAN138174258  

 ---------- --------------------------------------------------------- INTERVENTIONS-------------------------------------------------------- 

CATEGORY: NETWORK REPORT  

CREATION TIME:09/14/2021 16:05:30  

APPLICATION: SWIFT INTERFACE  

OPERATION: SYSTEM  

END TIME: 09/14/2021 16:34:17UTC+1  

TEXT (DEUTDEDBFRADE915007002406619050 00)  

:1)FO1 BPKOPLPW000018020215855/PL31102053560000180202158558 

 ---------------------------------------------------------------------------------------------------------------------------------- 

 

CONF DATE: September 14, 2021+++ 16:05:30+++ UTC+1 

+++ D-60437 FRANKFURT AM MAIN, GERMANY +++678 691 681  

MSG NO: 555TITLE: MT-103 GPI WIRE TRANSFER AUTHENTICATION MESSAGE CONFIRMATION LOGICAL ANSWER BACK? (YES)  

VALUE DATE/END TIME September 14, 2021+++ 16:34:17+++ UTC+1 MESSAGE HAS BEEN TRANSMITTED(01) 

 -------------------------------------------------------------------------------------------------------------------------------- 
MT 103 GPI ACKNOWLEDGMENT MESSAGE 
---- ----------------------------------------------------------------------------------------------------------------------------- 
QUOTE: DEUTSCHE BANK AG LOCATED AT TAUNUSANLAGE 12,60325 FRANKFURT AM MAIN GERMANY DO HEREBY BRING TO  

YOUR NOTICE  

THE ONGOING MT-103 GPI WIRE TRANSFER IN OUR BANK TO THE SUM OF: 980,000,000.00 #EURO# (Nine hundred and eighty thousand euros)  

IN YOUR FAVOR PMP PROSPERSP.ZO.O. THIS RECORD IN OUR BANK. 

***AUTOMATED FILE TRANSFER (AFT) DEUTSCHE BANK AG RESPONSE  

***VALIDATION SERVICE PROVIDER LOG FAIL/APPLICATION GENERATED REPORT  

***ACKNOWLEDGMENT & AUTHENTICATION ACK/NAG DELIVERY  

***FTA/FTI CONFORMANCE STATEMENT PASS/FAIL STATUS  

0050 CNT,-----------------------------------------------------VALID   

0060 RFF-DTM,-------------------------------------------------VALID   

0070 RFF,-----------------------------------------------------VALID   

0080 DTM,-----------------------------------------------------VALID   

0090 NAD-CTA-COM,---------------------------------------------VALID   

0100 NAD,-----------------------------------------------------VALID   

0110 CTA,-----------------------------------------------------VALID   

0120 COM,-----------------------------------------------------VALID   

0130 ERC-FTX-SG4,---------------------------------------------VALID   

0140 ERC,-----------------------------------------------------VALID   

0150 FTX,-----------------------------------------------------VALID   

TITLE   

PRT_TPZH ANSWER BACK AND ACKNOWLEDGEMENT MESSAGE AUTOMATED FILE TRANSFER (AFT) GATEWAY   

RESPONSE VALIDATION SERVICE PROVIDER LOG/APPLICATION GENERATED REPORT ACKNOWLEDGEMENT   

& AUTHENTICATION ACK NAG DELIVERY FTA/FTI CONFIRMATION STATEMENT PASS/FAIL STATUS   
  --------------------------------------------------------------------------------------------------------------------------------- 

ACKNOWLEDGEMENT RECEIPT DEUTDEBFRA   

STATUS: DELIVERED   

SENDER: DB-60437 FRANKFURT AM MAIN, GERMANY  

CATEGORY CODE: RF   

SEQUENCE/NUMBER: 421960  

END OF TRANSMISSION: 14-09-2021  

END TIME: 16:34:17 CET  

------------------------------------------------------SWIFT END CODE --------------------------------------------------------   

ACCESS CODE                : DE75454067BN7066    

RELEASE CODE               : DE93861747BN8117   

DOWNLOAD CODE              : DE6054593671889BND8472  

WITHDRAW PERMISSION CODE   : DE712SG3508DVY7  

DIRECTOR ID                : DEUT-HEBA37890672 

BONDINGKEY                 : JWSDB8872AN8527  

ACTIVATION CODE            : AM9384M1241670728908  

PIN CODE 1                 : DE000DB2G032  

PIN CODE 2                 : DE000DB2G3N 
------------------------------------------------------------------------------------------------------------------------ 

AUTHORIZED OFFICER   

CHIEF EXECUTIVE OFFICER   
